GLOBAL:
  QEMU_URI: qemu:///system
  VOLUME_PATH: /var/lib/libvirt/images
  #BASE_FOLDER: /etc/virt-compose
  BASE_FOLDER: .
  VM_FOLDER: vm
  METADATA_FOLDER: cloud-init
  BIN_FOLDER: /usr/bin
  SYSTEMD_FOLDER: /etc/systemd/system
  UDEV_RULES_FOLDER: /etc/udev/rules.d
